# Generated by Django 4.2.7 on 2024-01-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userdate_delete_datauser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDate',
            new_name='UserData',
        ),
    ]
